#!/usr/bin/env python

import argparse

from barhalbot import Bot

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Simple Meren Lab bot for barhal")
    parser.add_argument('--test-command', metavar="COMMAND", type=str, help="Test command.")

    Bot(parser.parse_args())
